name: "automation"

services:
  rails-app:
    image: 'wangkaihua/automation:v3'

    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"

    volumes:
      - "sqlite-data:/rails/db"

    ports:
      - '3000:3000'

    environment:
      # master key
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}


volumes:
  sqlite-data:
    driver: local